version: "3.9"
services:
  vectorstore:
    build:
      context: .
      dockerfile: Dockerfile.vectorstore
    container_name: synndicate-vectorstore
    environment:
      - UVICORN_WORKERS=1
    ports:
      - "8080:8080"
    restart: unless-stopped
