version: '3.8'

services:
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    container_name: synndicate-otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics
    depends_on:
      - jaeger
      - zipkin
    networks:
      - synndicate-tracing
    restart: unless-stopped

  # Jaeger all-in-one
  jaeger:
    image: jaegertracing/all-in-one:1.60
    container_name: synndicate-jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - synndicate-tracing
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:16686/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Zipkin
  zipkin:
    image: openzipkin/zipkin:3.4
    container_name: synndicate-zipkin
    ports:
      - "9411:9411"   # Zipkin UI and API
    environment:
      - STORAGE_TYPE=mem
    networks:
      - synndicate-tracing
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9411/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  synndicate-tracing:
    driver: bridge
    name: synndicate-tracing
