name: Semgrep Security Scan
on:
  pull_request:
  push:
    branches: [ main, develop ]
  schedule:
    # Run weekly security scans
    - cron: '0 6 * * 1'

jobs:
  semgrep:
    runs-on: ubuntu-latest
    name: Scan with Semgrep
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >
            p/ci
            p/python
            p/flask
            p/jwt
            p/secrets
            p/security-audit
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
