name: Simple Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test basic functionality
        run: |
          echo "✅ Checkout successful"
          ls -la
          echo "✅ Repository contents visible"
